"""End-to-end phone test (390x844) for the SlimTucci Workout Diary.
Local: python3 -m http.server 8765  then  python3 tests/e2e_test.py
Live:  BASE=https://slimtucci.github.io/workout-diary/ SHOTS=/path python3 tests/e2e_test.py"""
import json, sys, os, datetime, re
from playwright.sync_api import sync_playwright

BASE = os.environ.get("BASE", "http://localhost:8765/")
SHOTS = os.environ.get("SHOTS", "")
PREFIX = os.environ.get("SHOT_PREFIX", "")
results = []
def check(name, cond, detail=""):
    results.append((name, bool(cond), detail)); print(("PASS " if cond else "FAIL ") + name + (f"  [{detail}]" if detail else ""))
def shot(page, name):
    if SHOTS: page.screenshot(path=os.path.join(SHOTS, PREFIX + name))

TODAY = datetime.date.today()
SUN = TODAY - datetime.timedelta(days=(TODAY.weekday() + 1) % 7)   # Sunday of this week
SAT = SUN + datetime.timedelta(days=6)
iso = lambda d: d.isoformat()

def picker_search(page, q):
    page.fill("#pickQ", q); page.wait_for_timeout(50)
    return page.locator("#pickList .pick-row .pr-name").all_inner_texts()
def picker_pick(page, name):
    page.locator("#pickList .pick-row", has=page.locator(".pr-name", has_text=name)).first.click()
def picker_done(page):
    page.locator('.sheet-head [data-x="close"]').click(); page.wait_for_selector(".sheet-bg", state="detached")
def fill_set(card, si, w, r):
    card.locator(f'input[data-si="{si}"][data-k="weight"]').fill(str(w)); card.locator(f'input[data-si="{si}"][data-k="reps"]').fill(str(r))
def tap_day(page, d):
    page.click(f'.day[data-date="{iso(d)}"]'); page.wait_for_selector(f'#dayPanel[data-day="{iso(d)}"]')

with sync_playwright() as p:
    b = p.chromium.launch()
    ctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=3, is_mobile=True, has_touch=True, accept_downloads=True, color_scheme="light")
    # This run simulates a fresh install with nothing configured (no WHOOP Worker, no dashboard).
    # The configured states are tested further down against mocked Workers.
    ctx.route("**/config.js", lambda route: route.fulfill(status=200, content_type="application/javascript", body="window.SLIMTUCCI_CONFIG = { WHOOP_WORKER_URL: '', DASHBOARD_URL: '' };"))
    page = ctx.new_page()
    page.on("dialog", lambda d: d.accept())
    errors = []; page.on("pageerror", lambda e: (errors.append(str(e)), print("PAGEERROR", e.stack)))
    page.goto(BASE); page.wait_for_selector("#dayPanel")

    # ---- empty start ----
    st = page.evaluate("() => window.SlimTucci.state")
    check("starts with no workouts, templates or plans", len(st["sessions"]) == 0 and len(st["templates"]) == 0 and len(st.get("plans", [])) == 0)
    check("SlimTucci branding only", page.locator("#title").inner_text() == "SlimTucci" and "tuccigang" not in page.content().lower())
    sel = page.locator(".day.sel").get_attribute("data-date")
    check("today's day selected by default", sel == iso(TODAY), sel)
    empty = page.locator(".day-empty").inner_text()
    check("friendly empty state for the day", empty.startswith(f"No workouts on {TODAY.strftime('%a')}") and "tap + to log one" in empty, empty)
    check("welcome card shown on empty start", page.locator(".welcome").count() == 1)
    lib = page.evaluate("() => ({ n: window.SlimTucci.libSize, cats: window.SLIMTUCCI_LIBRARY.categories.map(c => [c.label, c.count]) })")
    check("library loaded with 300+ movements", lib["n"] >= 300, f"{lib['n']} · " + ", ".join(f"{l} {c}" for l, c in lib["cats"]))
    check("week strip starts Sunday", page.locator(".day").first.get_attribute("data-date") == iso(SUN))
    wk = page.evaluate("() => { const S = window.SlimTucci; return [S.weekStart('2026-10-04'), S.weekStart('2026-10-10'), S.weekStart('2026-10-11'), S.weekStart('2026-10-03')] }")
    check("Sun–Sat week math (Sun 4 & Sat 10 together, Sun 11 new week)", wk == ["2026-10-04", "2026-10-04", "2026-10-11", "2026-09-27"], str(wk))
    overflow = page.evaluate("() => document.scrollingElement.scrollWidth")
    check("no horizontal overflow at 390px", overflow <= 390, str(overflow))

    # ---- tap days ----
    tap_day(page, SUN)
    check("tapping Sunday selects it", page.locator(".day.sel").get_attribute("data-date") == iso(SUN) and page.locator(".day.sel").get_attribute("aria-pressed") == "true")
    check("day panel shows Sunday", page.locator(".day-title").inner_text().startswith("Sunday"), page.locator(".day-title").inner_text())
    check("Sunday empty state", "No workouts on Sun" in page.locator(".day-empty").inner_text())
    check("today still outlined", page.locator(f'.day.today[data-date="{iso(TODAY)}"]').count() == 1)

    # ---- Exercises tab: ONE merged list (no My/Library toggle), demo links, coaching cues ----
    page.click('.tabbar a[data-tab="exercises"]'); page.wait_for_selector("#exResults .ex-row")
    check("Exercises: single list, no My exercises / Library toggle", page.locator(".seg-btn").count() == 0 and page.locator("#app .seg").count() == 0 and page.locator('#app .chip[data-chip="mine"]').count() == 0)
    check("single list shows all 627 library movements", page.locator("#exResults .list-count").inner_text().startswith("627 exercises"), page.locator("#exResults .list-count").inner_text())
    allok = page.evaluate("""() => { const L = window.SLIMTUCCI_LIBRARY, S = window.SlimTucci; const bad = [];
      for (const [name] of L.items) { const u = S.demoUrl(name), c = S.libCues(name);
        const want = 'https://www.youtube.com/results?search_query=' + encodeURIComponent(name + ' exercise proper form').replace(/%20/g, '+');
        if (u !== want || !c || c.length < 2 || c.length > 4 || c.some(x => !x || x.length < 12)) bad.push(name); }
      return [L.items.length, bad, L.fields]; }""")
    check("every library item has a YouTube demo URL and 2–4 coaching cues", allok[0] == 627 and not allok[1] and allok[2][-1] == "cues", f"{allok[0]} items, bad: {allok[1][:5]}")
    page.fill("#exQ", "bulgrian split")   # typo on purpose
    names = page.locator("#exResults .pr-name").all_inner_texts()
    check("fuzzy search ('bulgrian split') finds Bulgarian Split Squat", any("Bulgarian Split Squat" == n for n in names), ", ".join(names[:4]))
    page.fill("#exQ", ""); page.click('#app .chip[data-chip="agility"]')
    ag = page.locator("#exResults .pr-name").all_inner_texts()
    check("category chip filters (Agility)", len(ag) >= 20 and "Lateral Shuffle" in ag, f"{len(ag)} shown")
    rows = page.locator("#exResults .ex-row").count()
    check("every list row has a small demo (play) icon", rows > 0 and page.locator("#exResults .ex-row .demo-ico").count() == rows and page.locator("#exResults .demo-ico").first.get_attribute("target") == "_blank")
    page.click('#app .chip[data-chip="all"]'); page.fill("#exQ", "copenhagen plank")
    cp = page.locator("#exResults .ex-row", has=page.locator(".pr-name", has_text="Copenhagen Plank")).first
    check("row demo link = YouTube search '<name> exercise proper form'", cp.locator(".demo-ico").get_attribute("href") == "https://www.youtube.com/results?search_query=Copenhagen+Plank+exercise+proper+form", cp.locator(".demo-ico").get_attribute("href"))
    page.locator("#exResults .ex-row .pr-name", has_text="Copenhagen Plank").first.click(); page.wait_for_selector("#watchDemo")
    wd = page.locator("#watchDemo")
    check("detail: 'Watch demo' button (play icon, new tab)", "Watch demo" in wd.inner_text() and wd.locator("svg").count() == 1 and wd.get_attribute("target") == "_blank" and wd.get_attribute("href").endswith("Copenhagen+Plank+exercise+proper+form"))
    cues = page.evaluate("() => window.SlimTucci.libCues('Copenhagen Plank')")
    check("detail: Notes/Cues pre-filled with the coaching cues", page.input_value("#exNotes") == "\n".join("• " + c for c in cues) and len(cues) >= 2, page.input_value("#exNotes")[:80])
    check("browsing a movement doesn't save it", not any(e["name"] == "Copenhagen Plank" for e in page.evaluate("() => window.SlimTucci.state.exercises")))
    page.evaluate("window.scrollTo(0,0)"); page.wait_for_timeout(100)
    shot(page, "15-exercise-detail.png")
    page.fill("#exNotes", "Knee on the bench first. Build to ankle.\nHips high, ribs down."); page.locator("#exNotes").blur()
    st_ex = [e for e in page.evaluate("() => window.SlimTucci.state.exercises") if e["name"] == "Copenhagen Plank"]
    check("editing cues saves the movement with his notes (override)", len(st_ex) == 1 and st_ex[0]["notesEdited"] and st_ex[0]["notes"].startswith("Knee on the bench") and page.evaluate("location.hash") == "#/exercise/" + st_ex[0]["id"])
    page.reload(); page.wait_for_selector("#exNotes")
    check("edited cues persist after reload", page.input_value("#exNotes") == "Knee on the bench first. Build to ankle.\nHips high, ribs down." and page.locator('[data-action="cues-reset"]').count() == 1)
    page.goto(BASE + "#/exercises"); page.wait_for_selector("#exResults"); page.fill("#exQ", "copenhagen plank")
    check("merged list is deduped by name (saved + library = one row)", page.locator("#exResults .pr-name").all_inner_texts().count("Copenhagen Plank") == 1)
    page.fill("#exQ", "Pickleball Ready Hop")
    page.click('#exResults [data-x="custom"]'); page.wait_for_selector("#exNotes")
    check("custom exercise: empty editable cues + Custom tag + demo link", page.input_value("#exNotes") == "" and page.locator(".exd-head .tag-custom").count() == 1 and page.locator("#watchDemo").get_attribute("href").endswith("Pickleball+Ready+Hop+exercise+proper+form"))
    page.goto(BASE + "#/exercises"); page.wait_for_selector("#exResults"); page.fill("#exQ", "")
    saved = page.evaluate("() => window.SlimTucci.state.exercises.map(e => e.name)")
    top = page.evaluate("(n) => [...document.querySelectorAll('#exResults .pr-name')].slice(0, n).map(el => el.firstChild.textContent.trim())", len(saved))
    check("saved + custom exercises lead the single list (then the library)", top == saved and "Copenhagen Plank" in saved and "Pickleball Ready Hop" in saved, f"{len(saved)} saved first")
    check("custom row shows a small 'Custom' tag", page.locator("#exResults .ex-row", has=page.locator(".pr-name", has_text="Pickleball Ready Hop")).locator(".tag-custom").count() == 1)
    page.locator("#toast").wait_for(state="hidden"); page.evaluate("document.activeElement.blur(); window.scrollTo(0,0)"); page.wait_for_timeout(150)
    shot(page, "14-exercises-list.png")

    # ---- template built with the picker ----
    page.goto(BASE + "#/templates"); page.wait_for_selector("#newTpl")
    check("templates empty state", page.locator(".empty-title").inner_text() == "No templates yet")
    page.fill("#newTpl", "Sunday Lateral Test"); page.click('[data-action="tpl-create"]'); page.wait_for_selector("#tName")
    page.click('[data-action="ti-add"]')
    r = picker_search(page, "landmine rot")
    check("picker: 'landmine rot' → Landmine Rotation first", r and r[0] == "Landmine Rotation", ", ".join(r[:3]))
    picker_pick(page, "Landmine Rotation")
    picker_search(page, "lateral bound"); picker_pick(page, "Lateral Bound")
    picker_done(page)
    names = page.locator(".ex-card .ex-name").all_inner_texts()
    check("template picker added 2 exercises (multi-add)", names == ["Landmine Rotation", "Lateral Bound"], str(names))
    check("library pick auto-added to My exercises with category", any(e["name"] == "Lateral Bound" and e["cat"] == "Power & Plyo" for e in page.evaluate("() => window.SlimTucci.state.exercises")))

    # ---- log a workout on Sunday via the day panel ----
    page.goto(BASE + "#/"); page.wait_for_selector("#dayPanel"); tap_day(page, SUN)
    page.locator('#dayPanel [data-action="day-add"]').last.click()
    page.click('.sheet [data-x="blank"]'); page.wait_for_selector("#sDate")
    check("blank workout is dated to the selected day", page.input_value("#sDate") == iso(SUN))
    check("log empty state + sticky Add/Finish bar", page.locator(".empty-title").inner_text() == "No exercises yet" and page.locator(".actionbar").is_visible())
    page.fill("#sName", "Sunday Strength")
    page.locator('.actionbar [data-action="add-ex"]').click()
    check("picker uses the same single list (no My/Library sections), saved first, with demo icons", page.locator("#pickList .sec-title").count() == 0 and page.locator("#pickList .pr-name").first.inner_text() == page.evaluate("() => window.SlimTucci.state.exercises[0].name") and page.locator("#pickList .ex-row .demo-ico").count() == page.locator("#pickList .ex-row").count())
    picker_search(page, "back squat"); picker_pick(page, "Barbell Back Squat")
    r = picker_search(page, "zercher")
    check("picker library search 'zercher'", "Zercher Squat" in r, ", ".join(r))
    picker_pick(page, "Zercher Squat")
    r = picker_search(page, "Tucci Scrum Drive Hold")
    check("picker offers Add custom when no match", page.locator('#pickList [data-x="custom"]').count() == 1)
    page.click('#pickList [data-x="custom"]')
    check("Done button counts adds", page.locator('.sheet-head [data-x="close"]').inner_text() == "Done (3)")
    picker_done(page)
    names = page.locator(".ex-card .ex-name").all_inner_texts()
    check("3 exercises added to workout", names == ["Barbell Back Squat", "Zercher Squat", "Tucci Scrum Drive Hold"], str(names))
    ex = page.evaluate("() => window.SlimTucci.state.exercises.map(e => [e.name, e.cat])")
    check("Zercher Squat auto-added to My exercises (Legs)", ["Zercher Squat", "Legs"] in ex)
    check("custom exercise saved to My exercises", any(n == "Tucci Scrum Drive Hold" for n, c in ex))
    sq = page.locator(".ex-card").nth(0)
    fill_set(sq, 0, 225, 5); sq.locator('[data-action="set-add"]').click(); sq = page.locator(".ex-card").nth(0)
    check("add set copies previous values", sq.locator('input[data-si="1"][data-k="weight"]').input_value() == "225")
    sq.locator('[data-action="set-add"]').click(); sq = page.locator(".ex-card").nth(0)
    sq.locator('[data-action="set-remove"][data-si="2"]').click(); sq = page.locator(".ex-card").nth(0)
    check("remove set works", sq.locator("tbody tr").count() == 2)
    sq.locator('[data-action="set-done"][data-si="0"]').click()
    check("done tick turns set green", sq.locator("tbody tr").first.get_attribute("class") == "done")
    fill_set(page.locator(".ex-card").nth(1), 0, 135, 8)
    page.locator("details.notes summary").first.click(); page.fill('textarea[data-bind="session"]', "Legs felt springy")
    page.locator(".ex-card").nth(0).locator("details.notes summary").click(); page.locator(".ex-card").nth(0).locator('textarea[data-bind="exnote"]').fill("Belt on top set")
    page.locator('.actionbar [data-action="finish"]').click(); page.wait_for_selector("#dayPanel")
    check("Finish returns to the workout's day", page.locator("#dayPanel").get_attribute("data-day") == iso(SUN))
    check("Sunday shows logged dot + session", page.locator(f'.day.has-log[data-date="{iso(SUN)}"]').count() == 1 and page.locator("#dayPanel .list-item .title").first.inner_text() == "Sunday Strength")

    # ---- plan a template on Saturday, then start it ----
    tap_day(page, SAT)
    page.click('#dayPanel [data-action="day-plan"]'); page.click('.sheet [data-x="plan"]')
    page.wait_for_selector("#dayPanel .planned")
    check("planned template shows on Saturday with a plan dot", page.locator("#dayPanel .planned .title").inner_text() == "Sunday Lateral Test" and page.locator(f'.day.has-plan[data-date="{iso(SAT)}"]').count() == 1)
    shot(page, "01-day-selected.png")
    page.click('#dayPanel [data-action="plan-start"]'); page.wait_for_selector("#sDate")
    check("starting the plan creates a workout dated Saturday from the template", page.input_value("#sDate") == iso(SAT) and page.locator(".ex-card .ex-name").all_inner_texts() == ["Landmine Rotation", "Lateral Bound"])
    fill_set(page.locator(".ex-card").nth(0), 0, 45, 8)
    page.locator('.actionbar [data-action="finish"]').click(); page.wait_for_selector("#dayPanel")
    check("plan replaced by logged session", page.locator("#dayPanel .planned").count() == 0 and page.locator(f'.day.has-log[data-date="{iso(SAT)}"]').count() == 1)

    # ---- last-time hint ----
    tap_day(page, TODAY) if SUN <= TODAY <= SAT else None
    page.goto(BASE + "#/"); page.wait_for_selector("#dayPanel")
    page.locator('#dayPanel [data-action="day-add"]').last.click(); page.click('.sheet [data-x="blank"]'); page.wait_for_selector("#sDate")
    page.fill("#sDate", iso(SAT + datetime.timedelta(days=1))); page.locator("#sDate").dispatch_event("change")
    page.locator('.actionbar [data-action="add-ex"]').click(); picker_search(page, "barbell back squat"); picker_pick(page, "Barbell Back Squat"); picker_done(page)
    last = page.locator(".ex-card .last").first.inner_text()
    check("'last time' hint shows previous sets", "225 × 5" in last, last)
    shot(page, "03-log-workout.png")
    page.click('[data-action="del-session"]'); page.wait_for_selector("#dayPanel")

    # ---- week arrows keep a selected day ----
    before = datetime.date.fromisoformat(page.locator(".day.sel").get_attribute("data-date"))
    page.click('[data-action="week-next"]')
    check("next week moves selection +7 days", page.locator(".day.sel").get_attribute("data-date") == iso(before + datetime.timedelta(days=7)) and page.locator(".day").first.get_attribute("data-date") == iso(SUN + datetime.timedelta(days=7)))
    page.click('[data-action="week-prev"]'); page.click('[data-action="week-prev"]')
    check("prev week arrow", page.locator(".day").first.get_attribute("data-date") == iso(SUN - datetime.timedelta(days=7)))
    page.click('[data-action="go-today"]')
    check("Today button returns to today", page.locator(".day.sel").get_attribute("data-date") == iso(TODAY))

    # ---- persistence across reload ----
    page.reload(); page.wait_for_selector("#dayPanel")
    st = page.evaluate("() => window.SlimTucci.state")
    s1 = [s for s in st["sessions"] if s["name"] == "Sunday Strength"]
    check("2 sessions persisted after reload", len(st["sessions"]) == 2, str(len(st["sessions"])))
    check("weights, done tick and notes persisted", s1 and [(x["weight"], x["reps"], x["done"]) for x in s1[0]["exercises"][0]["sets"]] == [("225", "5", True), ("225", "5", False)] and s1[0]["notes"] == "Legs felt springy" and s1[0]["exercises"][0]["notes"] == "Belt on top set",
          str(s1 and s1[0]["exercises"][0]["sets"]))
    tap_day(page, SUN)
    check("tapping Sunday after reload shows its workout", page.locator("#dayPanel .list-item .title").first.inner_text() == "Sunday Strength")

    # ---- history search ----
    page.click('.tabbar a[data-tab="history"]'); page.fill("#histQ", "zercher")
    check("history search by exercise", page.locator("#histList .list-item .title").all_inner_texts() == ["Sunday Strength"])
    page.fill("#histQ", "nothingmatches")
    check("history no-match state with Clear button", page.locator('[data-action="hist-clear"]').count() == 1)
    page.click('[data-action="hist-clear"]')
    check("history grouped by Sun–Sat week", page.locator(".week-group").first.get_attribute("data-week") == iso(SUN))

    # ---- picker screenshot ----
    page.goto(BASE + "#/"); page.wait_for_selector("#dayPanel"); page.locator('#dayPanel [data-action="day-add"]').last.click(); page.click('.sheet [data-x="blank"]'); page.wait_for_selector("#sDate")
    page.locator('.actionbar [data-action="add-ex"]').click(); picker_search(page, "lateral"); page.click('.sheet .chip[data-chip="agility"]'); page.wait_for_timeout(100)
    page.evaluate("document.activeElement.blur()"); page.wait_for_timeout(300)
    shot(page, "02-picker-search.png")
    picker_done(page); page.click('[data-action="del-session"]'); page.wait_for_selector("#dayPanel")


    # ---- macro calculator ----
    check("Macros tab in the bottom bar; Templates under More", page.locator('.tabbar a[data-tab="macros"]').count() == 1 and page.locator('.tabbar a[data-tab="templates"]').count() == 0)
    page.goto(BASE + "#/settings"); page.wait_for_selector('a.list-item[href="#/templates"]')
    check("More page links to Templates", page.locator('a.list-item[href="#/templates"]').count() == 1)
    page.goto(BASE + "#/"); page.wait_for_selector("#dayPanel")
    check("Today shows a 'set your macro targets' prompt before setup", page.locator("a.macro-mini.empty-mini").count() == 1)
    page.click('.tabbar a[data-tab="macros"]'); page.wait_for_selector("#mWeight")
    check("macro page empty state before inputs", "Enter your weight, height and age" in page.locator("#macroResults").inner_text())
    page.fill("#mWeight", "205"); page.fill("#mFt", "6"); page.fill("#mIn", "4"); page.fill("#mAge", "30")
    page.click('[data-action="macro-set"][data-k="activity"][data-v="moderate"]'); page.click('[data-action="macro-set"][data-k="goal"][data-v="maintain"]')
    got = [page.locator(sel).inner_text().replace("\n", "").replace(" kcal", "").replace(",", "").replace("g", "") for sel in ("#mCalories", "#mProtein", "#mCarbs", "#mFat")]
    meta = page.locator("#mMeta").inner_text()
    check("205 lb, 6'4\", 30 M, moderate, maintain → 3100 kcal · P185 · C435 · F70", got == ["3100", "185", "435", "70"], str(got))
    check("BMR 1991 / TDEE 3087 (Mifflin-St Jeor)", meta == "BMR 1,991 · TDEE 3,087 kcal · Mifflin-St Jeor", meta)
    check("% split shown (24/56/20)", [t.strip() for t in page.locator(".mc-pct").all_inner_texts()] == ["24%", "56%", "20%"])
    r = page.evaluate("() => window.SlimTucci.computeTargets({weightKg: 205/2.20462, heightCm: 76*2.54, age: 30, sex: 'male', activity: 'moderate', goal: 'maintain'})")
    check("computeTargets() hook matches UI", (r["calories"], r["protein"], r["carbs"], r["fat"], r["bmr"], r["tdee"]) == (3100, 185, 435, 70, 1991, 3087))
    r2 = page.evaluate("() => window.SlimTucci.computeTargets({weightKg: 205/2.20462, heightCm: 76*2.54, age: 30, sex: 'male', activity: 'moderate', goal: 'maintain'}, 400)")
    check("extraBurnKcal hook adds calories to carbs", r2["calories"] == 3500 and r2["protein"] == 185 and r2["carbs"] > r["carbs"], f"{r2['calories']} kcal, C {r2['carbs']}")
    page.locator("#toast").wait_for(state="hidden"); page.evaluate("document.activeElement.blur(); window.scrollTo(0,0)"); page.wait_for_timeout(200)
    shot(page, "05-macros.png")
    page.click(".how summary")
    how = page.locator(".how").inner_text()
    check("'How this was calculated' expander", "Mifflin-St Jeor BMR" in how and "× 1.55" in how and "Carbs fill the rest" in how)
    check("disclaimer shown", "Estimates only" in page.locator(".disclaimer").first.inner_text() and "coach" in page.locator(".disclaimer").first.inner_text())
    page.click('[data-action="macro-set"][data-k="goal"][data-v="cut"]')
    check("cut (standard −15%) → 2600 kcal, protein up to 205 g", page.locator("#mCalories").inner_text().startswith("2,600") and page.locator("#mProtein").inner_text().startswith("205"))
    page.click('[data-action="macro-set"][data-k="wUnit"][data-v="kg"]')
    check("kg toggle converts the value (93 kg) without changing targets", page.input_value("#mWeight") == "93" and page.locator("#mCalories").inner_text().startswith("2,600"), page.input_value("#mWeight"))
    page.click('[data-action="macro-set"][data-k="hUnit"][data-v="cm"]')
    check("cm toggle converts height (193 cm)", page.input_value("#mCm") == "193", page.input_value("#mCm"))
    page.fill("#mBf", "15")
    check("body-fat % switches BMR to Katch-McArdle", "Katch-McArdle" in page.locator("#mMeta").inner_text(), page.locator("#mMeta").inner_text())
    page.fill("#mBf", ""); page.click('[data-action="macro-set"][data-k="wUnit"][data-v="lb"]'); page.click('[data-action="macro-set"][data-k="hUnit"][data-v="ftin"]')
    page.click('[data-action="macro-set"][data-k="goal"][data-v="maintain"]')
    page.reload(); page.wait_for_selector("#mWeight")
    check("macro inputs persist after reload", (page.input_value("#mWeight"), page.input_value("#mFt"), page.input_value("#mIn"), page.input_value("#mAge")) == ("205", "6", "4", "30") and page.locator(".choice.on .ch-t").inner_text() == "Moderately active")
    check("latest result persists after reload", page.locator("#mCalories").inner_text().startswith("3,100"))
    page.goto(BASE + "#/"); page.wait_for_selector("#dayPanel")
    mini = page.locator("a.macro-mini").inner_text().replace("\n", " ")
    check("Today shows compact targets", "3,100" in mini and "185g" in mini and "435g" in mini and "70g" in mini, mini)

    # ---- v5: Burn today (manual) + WHOOP not-set-up state ----
    check("Burn today card on Today, below the targets strip", page.locator("#burnCard").count() == 1 and page.evaluate("() => { const m = document.querySelector('a.macro-mini'), c = document.getElementById('burnCard'); return !!(m.compareDocumentPosition(c) & Node.DOCUMENT_POSITION_FOLLOWING); }"))
    check("Burn today starts empty (tap to enter)", "Tap to enter calories burned" in page.locator("#burnCard").inner_text())
    ex = page.evaluate("() => [window.SlimTucci.computeBurnExtra(3600, 3087, 'maintain'), window.SlimTucci.computeBurnExtra(3600, 3087, 'cut'), window.SlimTucci.computeBurnExtra(3600, 3087, 'bulk'), window.SlimTucci.computeBurnExtra(2500, 3087, 'maintain'), window.SlimTucci.computeBurnExtra(9000, 3087, 'maintain')]")
    check("burn rule: maintain 3600 vs TDEE 3087 → +385 (75% of 513); cut +255; bulk +385; below TDEE 0; clamp 800", ex == [385, 255, 385, 0, 800], str(ex))
    page.click('#burnCard [data-action="burn-edit"]'); page.wait_for_selector("#burnInput")
    page.fill("#burnInput", "3600"); page.click('.sheet [data-x="burn-save"]'); page.wait_for_selector("#burnAdj")
    bc = page.locator("#burnCard").inner_text().replace("\n", " ")
    check("manual burn 3,600 → 'Adjusted for today: +385 kcal (+95 g carbs)'", "+385 kcal" in bc and "+95 g carbs" in bc and page.locator("#burnKcal").inner_text() == "3,600", bc)
    check("burn card labels the source Manual and explains the rule", page.locator("#burnCard .src-pill").inner_text() == "Manual" and "75% of your burn above your 3,08" in bc and "kcal TDEE, added as carbs" in bc and "3,485 kcal · C 530 g" in bc, bc)
    mini2 = page.locator("a.macro-mini").inner_text().replace("\n", " ")
    check("base targets strip unchanged by burn (3,100 · C 435g)", "3,100" in mini2 and "435g" in mini2 and mini2 == mini, mini2)
    adj = page.evaluate("() => { const a = window.SlimTucci.adjustedToday(); return [a.extra, a.adj.calories, a.adj.protein, a.adj.carbs, a.adj.fat, window.SlimTucci.caloriesBurnedToday()]; }")
    check("adjusted today = 3,485 kcal · P185 · C530 · F70 (all extra to carbs)", adj == [385, 3485, 185, 530, 70, 3600], str(adj))
    page.locator("#toast").wait_for(state="hidden"); page.evaluate("window.scrollTo(0, document.getElementById('dayPanel').getBoundingClientRect().top + window.scrollY - 70)"); page.wait_for_timeout(150)
    shot(page, "07-today-burn.png")
    page.reload(); page.wait_for_selector("#burnCard")
    bst = page.evaluate("() => window.SlimTucci.state.burn")
    check("manual burn persists after reload", bst and bst["kcal"] == 3600 and bst["source"] == "manual" and bst["date"] == iso(TODAY) and "+385 kcal" in page.locator("#burnCard").inner_text(), str(bst))
    page.click('.tabbar a[data-tab="macros"]'); page.wait_for_selector("#adjLine")
    al = page.locator("#adjLine").inner_text().replace("\n", " ")
    check("Macros: base targets unchanged + 'Adjusted today' line", page.locator("#mCalories").inner_text().startswith("3,100") and page.locator("#mCarbs").inner_text().startswith("435") and "Adjusted today: +385 kcal (+95 g carbs)" in al and "3,485 kcal" in al, al)
    check("Macros: WHOOP card below targets in not-set-up state", page.locator('#whoopCard .whoop-card[data-state="setup"]').count() == 1 and "Setup needed" in page.locator("#whoopCard").inner_text() and page.locator('#whoopCard [data-action="whoop-connect"]').inner_text() == "Connect WHOOP")
    page.locator("#whoopCard").scroll_into_view_if_needed(); page.wait_for_timeout(150)
    shot(page, "08-whoop-card-setup.png")
    page.click('#whoopCard [data-action="whoop-connect"]'); page.wait_for_selector(".setup-steps")
    check("Connect WHOOP (not set up) opens the friendly 'Setup needed' sheet with 3 steps", page.locator(".sheet h3").inner_text() == "Setup needed" and page.locator(".setup-steps li").count() == 3 and "Cloudflare" in page.locator(".setup-steps").inner_text())
    page.wait_for_timeout(600)
    shot(page, "09-whoop-setup-sheet.png")
    page.click('.sheet [data-x="manual"]'); page.wait_for_selector("#burnInput")
    check("setup sheet offers manual entry", page.input_value("#burnInput") == "3600")
    page.click('.sheet-head [data-x="close"]')
    page.goto(BASE + "#/settings"); page.wait_for_selector('a.list-item[href="#/whoop"]')
    check("More → Connections row (WHOOP · setup needed)", "WHOOP · setup needed" in page.locator('a.list-item[href="#/whoop"]').inner_text())
    page.click('a.list-item[href="#/whoop"]'); page.wait_for_selector("#whoopCard")
    check("Connections page renders with WHOOP card", page.locator("#title").inner_text() == "Connections" and page.locator('.tabbar a[data-tab="settings"].active').count() == 1)

    # ---- export ----
    page.goto(BASE + "#/settings")
    with page.expect_download() as dl: page.click('[data-action="export"]')
    data = json.load(open(dl.value.path()))
    check("export JSON includes sessions + plans + macros (+ burn)", data["app"] == "slimtucci-diary" and len(data["data"]["sessions"]) == 2 and "plans" in data["data"] and data["data"]["macros"]["result"]["calories"] == 3100 and data["data"]["burn"]["kcal"] == 3600)

    # ---- service worker / offline incl. library ----
    page.goto(BASE); page.evaluate("async () => { await navigator.serviceWorker.ready; }")
    page.reload(); page.wait_for_function("navigator.serviceWorker.controller !== null", timeout=15000)
    cache = page.evaluate("async () => { const ks = await caches.keys(); const c = await caches.open(ks[0]); return [ks, (await c.keys()).map(r => r.url.split('/').pop())]; }")
    SWV = re.search(r"VERSION = '([^']+)'", open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sw.js")).read()).group(1)
    check(f"SW cache {SWV} holds library + macro + config files", SWV in cache[0] and "exercises-library.js" in cache[1] and "macros-calc.js" in cache[1] and "config.js" in cache[1], str(cache[0]))
    ctx.set_offline(True); page.reload(); page.wait_for_selector("#dayPanel")
    check("offline: app + library load", page.evaluate("() => window.SlimTucci.libSize") >= 300)
    ctx.set_offline(False)

    # ---- dark mode render ----
    dctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=3, is_mobile=True, has_touch=True, color_scheme="dark")
    dctx.route("**/config.js", lambda route: route.fulfill(status=200, content_type="application/javascript", body="window.SLIMTUCCI_CONFIG = { WHOOP_WORKER_URL: '', DASHBOARD_URL: '' };"))
    dp = dctx.new_page(); dp.on("pageerror", lambda e: errors.append(str(e)))
    dp.goto(BASE); dp.wait_for_selector("#dayPanel")
    bg = dp.evaluate("() => getComputedStyle(document.body).backgroundColor")
    check("auto dark mode via prefers-color-scheme", bg == "rgb(14, 20, 22)", bg)
    shot(dp, "04-dark-mode.png")
    dp.goto(BASE + "#/macros"); dp.wait_for_selector("#mWeight")
    dp.fill("#mWeight", "205"); dp.fill("#mFt", "6"); dp.fill("#mIn", "4"); dp.fill("#mAge", "30")
    hero = dp.evaluate("() => { const e = document.querySelector('.macro-hero'); const cs = getComputedStyle(e); return [cs.backgroundColor, cs.color]; }")
    check("macro page in dark mode (teal hero, dark ink)", hero == ["rgb(45, 212, 191)", "rgb(4, 47, 43)"] and dp.locator("#mCalories").inner_text().startswith("3,100"), str(hero))
    dp.evaluate("document.activeElement.blur(); window.scrollTo(0,0)"); dp.wait_for_timeout(200)
    shot(dp, "06-macros-dark.png")
    dp.fill("#mWeight", "205"); dp.evaluate("document.activeElement.blur()")
    dp.goto(BASE + "#/"); dp.wait_for_selector("#burnCard")
    dp.click('#burnCard [data-action="burn-edit"]'); dp.fill("#burnInput", "3600"); dp.click('.sheet [data-x="burn-save"]'); dp.wait_for_selector("#burnAdj")
    adjc = dp.evaluate("() => { const cs = getComputedStyle(document.getElementById('burnAdj')); return [cs.backgroundColor, cs.color]; }")
    check("dark mode: Burn today card (teal tint) + adjustment", "+385 kcal" in dp.locator("#burnAdj").inner_text() and adjc[1] == "rgb(94, 234, 212)", str(adjc))
    dp.locator("#toast").wait_for(state="hidden"); dp.evaluate("window.scrollTo(0, document.getElementById('dayPanel').getBoundingClientRect().top + window.scrollY - 70)"); dp.wait_for_timeout(150)
    shot(dp, "10-today-burn-dark.png")
    dp.goto(BASE + "#/macros"); dp.wait_for_selector("#whoopCard"); dp.locator("#whoopCard").scroll_into_view_if_needed(); dp.wait_for_timeout(150)
    pill = dp.evaluate("() => getComputedStyle(document.querySelector('#whoopCard .status-pill')).color")
    check("dark mode: WHOOP card renders (amber 'Setup needed' pill)", dp.locator('#whoopCard [data-state="setup"]').count() == 1 and pill == "rgb(251, 191, 36)", pill)
    shot(dp, "11-whoop-card-dark.png")
    dp.goto(BASE + "#/exercises"); dp.wait_for_selector("#exResults .ex-row"); dp.fill("#exQ", "barbell back squat")
    dp.locator("#exResults .ex-row .pr-name", has_text="Barbell Back Squat").first.click(); dp.wait_for_selector("#watchDemo")
    dbtn = dp.evaluate("() => { const cs = getComputedStyle(document.getElementById('watchDemo')); return [cs.backgroundColor, cs.color, getComputedStyle(document.getElementById('exNotes')).color]; }")
    check("dark mode: exercise detail (demo button + cues readable)", dbtn[0] == "rgb(220, 38, 38)" and dbtn[1] == "rgb(255, 255, 255)" and dbtn[2] == "rgb(232, 238, 240)" and dp.input_value("#exNotes").startswith("• "), str(dbtn))
    dp.evaluate("document.activeElement.blur(); window.scrollTo(0,0)"); dp.wait_for_timeout(150)
    shot(dp, "16-exercise-detail-dark.png")

    # ---- v5: WHOOP ready + connected states with a mocked Worker (no real WHOOP / Cloudflare) ----
    MOCK = "https://slimtucci-whoop.mock-worker.test"
    SID = "Sx7kQ2mZ9pLr4TbV1nWc8yHd3fJg6aEu"
    seen = {"auth": [], "today": [], "disconnect": []}
    wctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=3, is_mobile=True, has_touch=True, color_scheme="light", service_workers="block")
    wctx.route("**/config.js", lambda route: route.fulfill(status=200, content_type="application/javascript", body=f"window.SLIMTUCCI_CONFIG = {{ WHOOP_WORKER_URL: '{MOCK}/' }};"))
    CORS = {"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Authorization, Content-Type", "Access-Control-Allow-Methods": "GET, POST, OPTIONS"}
    def worker(route):
        req = route.request; path = req.url.replace(MOCK, "").split("?")[0]
        if req.method == "OPTIONS": return route.fulfill(status=204, headers=CORS)
        if path == "/auth/start": seen["auth"].append(req.url); return route.fulfill(status=200, content_type="text/html", body="<h1>mock WHOOP login</h1>")
        if path == "/today":
            seen["today"].append(req.headers.get("authorization"))
            if req.headers.get("authorization") != f"Bearer {SID}": return route.fulfill(status=401, headers=CORS, content_type="application/json", body='{"error":"reconnect_needed"}')
            return route.fulfill(status=200, headers=CORS, content_type="application/json", body=json.dumps({"kcal": 3600, "kilojoule": 15062.4, "score_state": "SCORED", "in_progress": True, "cycle_start": iso(TODAY) + "T06:00:00.000Z", "fetched_at": "x"}))
        if path == "/disconnect": seen["disconnect"].append(req.headers.get("authorization")); return route.fulfill(status=200, headers=CORS, content_type="application/json", body='{"ok":true}')
        return route.fulfill(status=404, headers=CORS, body="")
    wctx.route(MOCK + "/**", worker)
    wp = wctx.new_page(); wp.on("pageerror", lambda e: errors.append("whoop: " + str(e)))
    wp.goto(BASE + "#/macros"); wp.wait_for_selector("#mWeight")
    wp.fill("#mWeight", "205"); wp.fill("#mFt", "6"); wp.fill("#mIn", "4"); wp.fill("#mAge", "30"); wp.evaluate("document.activeElement.blur()")
    check("WHOOP configured → card shows 'Not connected' + Connect", wp.locator('#whoopCard [data-state="ready"]').count() == 1 and wp.evaluate("() => window.SlimTucci.whoopConfigured()"))
    wp.click('#whoopCard [data-action="whoop-connect"]'); wp.wait_for_url(MOCK + "/auth/start")
    check("Connect redirects to WORKER_URL/auth/start", seen["auth"] == [MOCK + "/auth/start"], str(seen["auth"]))
    wp.goto(BASE + "#/whoop?session=" + SID); wp.wait_for_selector('#whoopCard [data-state="connected"]'); wp.wait_for_function("document.getElementById('whoopKcal') && document.getElementById('whoopKcal').textContent === '3,600'")
    check("OAuth return: session stored, removed from URL, connected sheet shown", wp.evaluate("location.hash") == "#/whoop" and wp.locator(".sheet h3").inner_text() == "WHOOP connected" and wp.locator("#sessCode").inner_text() == SID)
    wraw = wp.evaluate("() => localStorage.getItem('slimtucci-whoop-v1')")
    wobj = json.loads(wraw)
    check("device stores only a session id (no WHOOP tokens)", wobj["session"] == SID and "token" not in wraw.lower() and set(wobj) <= {"session", "connectedAt", "lastSync", "today", "error"}, wraw)
    check("/today called with Bearer session", seen["today"] and all(h == f"Bearer {SID}" for h in seen["today"]), str(seen["today"]))
    wp.click('.sheet [data-x="close"]')
    wc = wp.locator("#whoopCard").inner_text().replace("\n", " ")
    check("connected card: 'Connected · last synced', today's kcal, Refresh + Disconnect", "Connected · last synced" in wc and "3,600" in wc and wp.locator('#whoopCard [data-action="whoop-refresh"]').count() == 1 and wp.locator('#whoopCard [data-action="whoop-disconnect"]').count() == 1, wc)
    shot(wp, "12-whoop-connected.png")
    n0 = len(seen["today"]); wp.click('#whoopCard [data-action="whoop-refresh"]'); wp.wait_for_function(f"document.getElementById('toast').textContent === 'WHOOP synced'")
    check("Refresh re-fetches /today", len(seen["today"]) == n0 + 1)
    wp.goto(BASE + "#/"); wp.wait_for_selector("#burnAdj")
    wb = wp.locator("#burnCard").inner_text().replace("\n", " ")
    check("Today burn from WHOOP (source WHOOP) → +385 kcal (+95 g carbs)", wp.locator("#burnCard .src-pill").inner_text() == "WHOOP" and "3,600" in wb and "+385 kcal" in wb and "+95 g carbs" in wb, wb)
    check("WHOOP connected: base strip still 3,100", "3,100" in wp.locator("a.macro-mini").inner_text())
    wp.locator("#toast").wait_for(state="hidden"); wp.evaluate("window.scrollTo(0, document.getElementById('dayPanel').getBoundingClientRect().top + window.scrollY - 70)"); wp.wait_for_timeout(150)
    shot(wp, "13-today-burn-whoop.png")
    wp.click('#burnCard [data-action="burn-edit"]'); wp.fill("#burnInput", "3200"); wp.click('.sheet [data-x="burn-save"]'); wp.wait_for_selector("#burnAdj")
    check("manual entry overrides WHOOP for today", wp.locator("#burnCard .src-pill").inner_text() == "Manual" and "+85 kcal" in wp.locator("#burnAdj").inner_text(), wp.locator("#burnAdj").inner_text())
    wp.goto(BASE + "#/whoop"); wp.wait_for_selector('#whoopCard [data-state="connected"]')
    wp.on("dialog", lambda d: d.accept())
    wp.click('#whoopCard [data-action="whoop-disconnect"]'); wp.wait_for_selector('#whoopCard [data-state="ready"]'); wp.wait_for_timeout(300)
    check("Disconnect: POST /disconnect with session, local session cleared", seen["disconnect"] == [f"Bearer {SID}"] and "session" not in json.loads(wp.evaluate("() => localStorage.getItem('slimtucci-whoop-v1')")), str(seen["disconnect"]))
    wp.goto(BASE + "#/whoop?session=bad"); wp.wait_for_selector('#whoopCard [data-state="ready"]')
    check("bad session in return URL is rejected safely", wp.evaluate("location.hash") == "#/whoop" and "connection failed" in wp.locator("#whoopCard").inner_text().lower())
    wctx.close()

    # ---- v8: Dashboard sync with a mocked admin Worker (the real endpoint is tested in the Worker repo) ----
    DMOCK = "https://slimtucci-admin.mock-worker.test"
    TOK = "stds_Zq3vN8xR1kLm5TbW7pYc2HdF9gJs4aEu0oQiXy6Vn1M"
    BADTOK = "stds_" + "B" * 43
    posts = []; mode = {"status": 200}
    DCORS = {"Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "Authorization, Content-Type", "Access-Control-Allow-Methods": "POST, OPTIONS"}
    def dworker(route):
        req = route.request; path = req.url.replace(DMOCK, "").split("?")[0]
        if req.method == "OPTIONS": return route.fulfill(status=204, headers=DCORS)
        if path == "/admin/api/diary-sync" and req.method == "POST":
            auth = req.headers.get("authorization"); posts.append({"auth": auth, "body": json.loads(req.post_data)})
            if auth != f"Bearer {TOK}" or mode["status"] == 401: return route.fulfill(status=401, headers=DCORS, content_type="application/json", body='{"error":"unauthorized"}')
            return route.fulfill(status=mode["status"], headers=DCORS, content_type="application/json", body='{"ok":true}')
        return route.fulfill(status=404, headers=DCORS, body="")
    sctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=3, is_mobile=True, has_touch=True, color_scheme="light", service_workers="block", accept_downloads=True)
    sctx.route("**/config.js", lambda route: route.fulfill(status=200, content_type="application/javascript", body=f"window.SLIMTUCCI_CONFIG = {{ WHOOP_WORKER_URL: '', DASHBOARD_URL: '{DMOCK}' }};"))
    sctx.route(DMOCK + "/**", dworker)
    sp = sctx.new_page(); sp.on("pageerror", lambda e: errors.append("dash: " + str(e))); sp.on("dialog", lambda d: d.accept())
    sp.clock.install()
    sp.goto(BASE + "#/settings"); sp.wait_for_selector('a.list-item[href="#/dashsync"]')
    check("More → Connections has 'Dashboard sync · Not connected'", "Dashboard sync" in sp.locator('a.list-item[href="#/dashsync"]').inner_text() and sp.locator("#dashSyncSub").inner_text() == "Not connected")
    sp.clock.run_for(3000)
    check("not connected → nothing is sent on open", posts == [], str(len(posts)))
    sp.click('a.list-item[href="#/dashsync"]'); sp.wait_for_selector("#dashToken")
    check("Dashboard sync page: title + paste field + Connect", sp.locator("#title").inner_text() == "Dashboard sync" and sp.locator('[data-action="dash-connect"]').is_visible())
    shot(sp, "17-dashboard-sync-connect.png")
    sp.fill("#dashToken", "hello"); sp.click('[data-action="dash-connect"]'); sp.wait_for_timeout(100)
    check("malformed code rejected locally (nothing sent, nothing stored)", posts == [] and sp.evaluate("() => localStorage.getItem('slimtucci-dashsync-v1')") in (None, "{}") and "doesn’t look right" in sp.locator("#toast").inner_text())
    sp.fill("#dashToken", BADTOK); sp.click('[data-action="dash-connect"]'); sp.wait_for_selector(".wc-err")
    check("code refused by the dashboard → error shown, code not kept", len(posts) == 1 and "didn’t work" in sp.locator(".wc-err").inner_text() and "token" not in json.loads(sp.evaluate("() => localStorage.getItem('slimtucci-dashsync-v1')")))
    posts.clear()
    sp.fill("#dashToken", "  " + TOK + " "); sp.click('[data-action="dash-connect"]'); sp.wait_for_selector("#dashSyncStatus")
    body = posts[0]["body"] if posts else {}
    check("Connect sends one POST with Bearer code", len(posts) == 1 and posts[0]["auth"] == f"Bearer {TOK}", str(len(posts)))
    check("payload = Export shape, workout data only (no macros, burn or WHOOP)", body.get("app") == "slimtucci-diary" and body.get("version") == 1 and "exportedAt" in body and sorted(body["data"].keys()) == ["exercises", "plans", "sessions", "settings", "templates", "version"], str(sorted(body.get("data", {}).keys())))
    check("status line 'Synced just now'", sp.locator("#dashSyncStatus").inner_text() == "Synced just now", sp.locator("#dashSyncStatus").inner_text())
    ls = sp.evaluate("() => [localStorage.getItem('slimtucci-dashsync-v1'), localStorage.getItem('slimtucci-diary-v1')]")
    check("code stored only in its own key (slimtucci-dashsync-v1), not in diary data", TOK in ls[0] and TOK not in (ls[1] or ""))
    sp.clock.run_for(2 * 60 * 1000 + 5000); sp.goto(BASE + "#/settings"); sp.wait_for_selector("#dashSyncSub")
    check("quiet status in More: 'Synced 2 min ago'", sp.locator("#dashSyncSub").inner_text() == "Synced 2 min ago", sp.locator("#dashSyncSub").inner_text())
    shot(sp, "18-more-dashboard-synced.png")
    n0 = len(posts)
    with sp.expect_download() as dl: sp.click('[data-action="export"]')
    exp_txt = open(dl.value.path()).read()
    check("Export JSON never contains the sync code", TOK not in exp_txt and "dashsync" not in exp_txt and json.loads(exp_txt)["app"] == "slimtucci-diary")
    sp.goto(BASE + "#/"); sp.wait_for_selector("#dayPanel")
    sp.locator('#dayPanel [data-action="day-add"]').last.click(); sp.click('.sheet [data-x="blank"]'); sp.wait_for_selector("#sDate")
    sp.fill("#sName", "Sync Check Session"); sp.evaluate("document.activeElement.blur()")
    n1 = len(posts)
    sp.clock.run_for(20000)
    check("change → no POST before the 30 s debounce", len(posts) == n1, f"{n0}->{len(posts)}")
    sp.clock.run_for(15000); sp.wait_for_timeout(200)
    check("change → one POST ~30 s later with the new workout", len(posts) == n1 + 1 and any(x.get("name") == "Sync Check Session" for x in posts[-1]["body"]["data"]["sessions"]), str(len(posts) - n1))
    sp.clock.run_for(60000); sp.wait_for_timeout(100)
    check("no repeat POST when nothing changed", len(posts) == n1 + 1)
    sp.reload(); sp.wait_for_selector("#app"); sp.clock.run_for(3000); sp.wait_for_timeout(200)
    check("app open → syncs", len(posts) == n1 + 2, str(len(posts) - n1))
    mode["status"] = 401
    sp.goto(BASE + "#/dashsync"); sp.wait_for_selector("#dashSyncStatus"); sp.click('[data-action="dash-sync-now"]'); sp.wait_for_timeout(300)
    check("revoked code → 'Sync code no longer works' status", "no longer works" in sp.locator("#dashSyncStatus").inner_text(), sp.locator("#dashSyncStatus").inner_text())
    mode["status"] = 200
    sp.click('[data-action="dash-disconnect"]'); sp.wait_for_selector("#dashToken")
    check("Disconnect removes the code from this phone", "token" not in json.loads(sp.evaluate("() => localStorage.getItem('slimtucci-dashsync-v1')") or "{}"))
    sctx.close()
    check("no JS errors", not errors, "; ".join(errors))
    b.close()

fails = [r for r in results if not r[1]]
print(f"\n{len(results) - len(fails)}/{len(results)} checks passed")
sys.exit(1 if fails else 0)
